fix version of base64
for this error:

 Error: The application encountered the following error: You have
 already activated base64 0.1.1, but your Gemfile requires base64 0.2.0.
 Since base64 is a default gem, you can either remove your dependency on
 it or try updating to a newer version of bundler that supports base64
 as a default gem. (Gem::LoadError)